### ISSUE TITLE
The Fragments which form the part of steps, expand according to the amount of widget or data contained in them

### ISSUE THREAD

**Issue by vivek22joshi** [shivasurya/materialsteppers#14]
Hello Surya
Great work by the way.
FormFragment, TextFragment, Instruction, they all expand or take as much place as per the amount of widgets or data stored.
For example let's Form Fragment. To the parent in the XML apply a dark background. what you'll see is that dark background only cover 1/4th while running on real device but cover entire screen in android studio. 
Similarly I tried changing various layouts but didn't work. Please look into this matter.

**Comment by omerarshad** [comment]
yes this happens. please fix it

**Comment by shivasurya** [comment]
Respected,
Thanks for mentioning.
I've implemented scrollview so that you can fragment layout will be flexible Enough to show small or large number of widgets.
The thing is dark background shows odd behavior may be I can add some fixes to match the layout background of fragment. Rite ?
Stay tune, rolling out new features and bug fixes in a week.

**Comment by ColinWa** [comment]
This issue remains unfixed. 
All layouts for fragments are forced to same height and that is the height of the fragment layout with the most widgets. 
This causes fragments with fewer widgets to have a so much empty space below the last widget that is scrollable.

This issue is same with closed issue #12
